[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#111827"
secondaryBackgroundColor = "#1f2937"
textColor = "#f9fafb"

[client]
toolbarMode = "minimal"
